### ISSUE TITLE
Code 400 error

### ISSUE THREAD

**Issue by dougbrowning** [Esri/Survey123Community#137]
Keep getting a Code 400 Cannot perform operation.  Invalid operation parameters.  Error when submitting a form.  Strangely if I edit the submission, change nothing at all, then submit again it works.

I have tried remaking the form several times.  Moved on to the next form and it is doing the same thing.  My first form did none of this.  

Any hints?

Only thing it may be is that it at first complained that my selection list values (not labels) could not have spaces in them (which really needs to be fixed).  I did take out the spaces and it built but maybe it is left over somewhere?  It is a rather simple form (see below).

![image](https://cloud.githubusercontent.com/assets/6051277/8988993/3b374e6a-369e-11e5-867f-bb39ddd407d6.png)

![image](https://cloud.githubusercontent.com/assets/6051277/8989002/4da8a6e8-369e-11e5-85b0-83462fce906c.png)

**Comment by survey123** [comment]
I have tried (and failed) to reproduce your issue. Is there any way you could provide a copy of your original spreadsheet? You can email us at survey123@esri.com

**Comment by dougbrowning** [comment]
Here is the whole folder.  Still getting error.
thanks
 


     On Tuesday, August 11, 2015 5:17 PM, Survey123 <notifications@github.com> wrote:
   
 

 I have tried (and failed) to reproduce your issue. Is there any way you could provide a copy of your original spreadsheet? You can email us at survey123@esri.com—

**Comment by survey123** [comment]
Closing. [Addressed in International Children's Book Release] (https://geonet.esri.com/groups/survey123/blog/2016/04/11/international-childrens-book-day-release)

**Comment by chvandev** [comment]
I have the latest version of survey123 (1.3.38) and am still getting Code 400 errors. I have a survey created, collect data (some with and some without photos) and when I go to upload them, none will upload. I get "This survey was not able to be sent due to the following error: Code 400 Invalid URL"

I've had some surveys load fine recently, but the most recent one I'm working with will not upload. I have 23 surveys waiting in my Outbox.
Help!
Thanks,
Chris

**Comment by survey123** [comment]
Chris.
We will follow up with you with a phone call.
Please send us your contact info to survey123@esri.com so we can get more details. Please reference this issue in your email.
